### ISSUE TITLE
BeforeSend not working

### ISSUE THREAD

**Issue by Kumzy** [jkleroy/XojoSentry#1]
Issue: The method BeforeSend is not working

In the method **SubmitException**, data is JSON is generated from dictionary and BeforeSend is called after with the dictionnary in parameter. 

Solution: I think the BeforeSend should be call before the convertion in String with GenerateJSON

Xojo: 2022r4.1
Platform: MacOS

Should I do a pull request?

**Comment by jkleroy** [comment]
Fixed
