### ISSUE TITLE
web_GetBrowserInfo Missing Code

### ISSUE THREAD

**Issue by patricksalo** [jkleroy/XojoSentry#11]
Hi Jeremie,

When copying Xojo_Sentry from the example project, the debugger flags the web_GetBrowserInfo method with the following error...

![Screenshot 2024-06-03 at 7 27 46 PM](https://github.com/jkleroy/XojoSentry/assets/70122368/35d9e684-9e1e-4516-b709-d8230bf0c801)

Assuming this should be something along the lines of...
![Screenshot 2024-06-03 at 7 28 11 PM](https://github.com/jkleroy/XojoSentry/assets/70122368/1495cb3a-5b0a-44be-8d12-acace1608453)

Patrick

**Comment by jkleroy** [comment]
Fixed
