### ISSUE TITLE
11 Errors when I Compile Desktop Example

### ISSUE THREAD

**Issue by Schellhammer** [jkleroy/XojoSentry#12]
Xojo 2024 r1.1, MacBook Air M1

This Item does not Exists
sp.parent_span_id = **transaction**.span.id

![Bildschirmfoto 2024-06-19 um 09 05 01](https://github.com/jkleroy/XojoSentry/assets/27682524/770e5ecd-edd6-4358-887c-4b3c7533cf16)

**Comment by jkleroy** [comment]
Fixed
