### ISSUE TITLE
Error building for windows

### ISSUE THREAD

**Issue by Kumzy** [jkleroy/XojoSentry#4]
Error compiling on Windows

Type mismatch error. Expected class Xojo.Core.MemoryBlock, but got Ptr

in GenerateJSON file:

`dim res as Xojo.Core.MemoryBlock = r`

**Comment by eurog33k** [comment]
replace that line with 
dim res As New Xojo.Core.MemoryBlock(r,o)

**Comment by jkleroy** [comment]
Fixed
